USE database VISION
CREATE schema VISIONBOOKS
USE schema VISIONBOOKS
-- tables
CREATE TABLE IF NOT EXISTS AUTHORS (
    AU_ID VARCHAR(20) NOT NULL,
    AU_LNAME VARCHAR(40) NOT NULL,
    AU_FNAME VARCHAR(20) NOT NULL,
    PHONE CHAR(12) NOT NULL,
    ADDRESS VARCHAR(40) NULL,
    CITY VARCHAR(20) NULL,
    STATE CHAR(2) NULL,
    ZIP CHAR(5) NULL,
    CONTRACT BOOLEAN NOT NULL,
    CONSTRAINT PK_AUTHORS PRIMARY KEY (AU_ID)
);

CREATE or REPLACE TABLE DISCOUNTS (
    DISCOUNT_ID VARCHAR(40) NOT NULL,
    SALES_ID VARCHAR(40) NOT NULL,
    LOWQTY SMALLINT NULL,
    HIGHQTY SMALLINT NULL,
    DISCOUNT DECIMAL(4,2) NOT NULL,
    CONSTRAINT PK_DISCOUNTS PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS PUBLISHERS (
    PUB_ID CHAR(4) NOT NULL,
    PUB_NAME VARCHAR(40) NULL,
    CITY VARCHAR(20) NULL,
    STATE CHAR(2) NULL,
    COUNTRY VARCHAR(30) NULL,
    CONSTRAINT PK_PUBLISHERS PRIMARY KEY (PUB_ID)
);

CREATE TABLE IF NOT EXISTS READER (
    READER_ID VARCHAR(40) NOT NULL,
    READER_EMAIL VARCHAR(40) NOT NULL,
    READER_PASSWORD VARCHAR(20) NOT NULL,
    CONSTRAINT PK_READER PRIMARY KEY (READER_ID)
);

CREATE OR REPLACE TABLE  READERSALES (
    READER_ID CHAR(40) NOT NULL,
    SALES_ID VARCHAR(40) NOT NULL,
    CONSTRAINT PK_READERSALES PRIMARY KEY (SALES_ID)
);

CREATE TABLE IF NOT EXISTS SALES (
    ORD_DATE DATETIME NOT NULL,
    PAYTERMS VARCHAR(12) NOT NULL,
    QTY SMALLINT NOT NULL,
    SALES_ID VARCHAR(40) NOT NULL,
    TITLE_ID VARCHAR(40) NOT NULL,
    CONSTRAINT PK_SALES PRIMARY KEY (SALES_ID)
);

CREATE TABLE IF NOT EXISTS TITLEAUTHORS (
    AU_ID VARCHAR(20) NOT NULL,
    TITLE_ID VARCHAR(40) NOT NULL,
    AU_ORD SMALLINT NOT NULL,
    ROYALTYPER INT NOT NULL,
    CONSTRAINT PK_TITLEAUTHORS PRIMARY KEY (AU_ID, TITLE_ID)
);

CREATE TABLE IF NOT EXISTS TITLES (
    TITLE_ID VARCHAR(40) NOT NULL,
    TITLE VARCHAR(80) NOT NULL,
    TYPE CHAR(12) NOT NULL,
    PUB_ID CHAR(4) NOT NULL,
    PRICE NUMBER(19,4) NULL,
    ADVANCE NUMBER(19,4) NULL,
    ROYALTY INT NULL,
    YTD_SALES INT NULL,
    NOTES VARCHAR(200) NULL,
    PUBTIME DATETIME NOT NULL,
    CONSTRAINT PK_TITLES PRIMARY KEY (TITLE_ID)
);

-- foreign keys
ALTER TABLE DISCOUNTS 
ADD CONSTRAINT FK_DISCOUNTS_SALES 
FOREIGN KEY (SALES_ID) 
REFERENCES SALES (SALES_ID);

ALTER TABLE READERSALES 
ADD CONSTRAINT FK_READERSALES_READER 
FOREIGN KEY (READER_ID) 
REFERENCES READER (READER_ID);

ALTER TABLE READERSALES 
ADD CONSTRAINT FK_READERSALES_SALES 
FOREIGN KEY (SALES_ID) 
REFERENCES SALES (SALES_ID);

ALTER TABLE SALES 
ADD CONSTRAINT FK_SALES_TITLES 
FOREIGN KEY (TITLE_ID) 
REFERENCES TITLES (TITLE_ID);

ALTER TABLE TITLEAUTHORS 
ADD CONSTRAINT FK_TITLEAUTHORS_AUTHORS 
FOREIGN KEY (AU_ID) 
REFERENCES AUTHORS (AU_ID);

ALTER TABLE TITLEAUTHORS 
ADD CONSTRAINT FK_TITLEAUTHORS_TITLES 
FOREIGN KEY (TITLE_ID) 
REFERENCES TITLES (TITLE_ID);

ALTER TABLE TITLES 
ADD CONSTRAINT FK_TITLES_PUBLISHERS 
FOREIGN KEY (PUB_ID) 
REFERENCES PUBLISHERS (PUB_ID);
