USE database VISION
CREATE schema VISIONFLIX
USE schema VISIONFLIX
-- tables
CREATE TABLE IF NOT EXISTS ACCOUNT_ACTIVITY (
    ACTIVITY_ID INT NOT NULL,
    LOGIN_TIME TIMESTAMP NOT NULL,
    LOGOUT_TIME TIMESTAMP NULL,
    ACCOUNT_ID INT NOT NULL,
    CONSTRAINT PK_ACCOUNT_ACTIVITY PRIMARY KEY (ACTIVITY_ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT_BILLING (
    BILLING_ID INT NOT NULL,
    BILLING_DATE DATETIME NOT NULL,
    ACCOUNT_ID INT NOT NULL,
    PLAN_ID INT NOT NULL,
    CONSTRAINT PK_ACCOUNT_BILLING PRIMARY KEY (BILLING_ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT_TITLES (
    TITLE_ACCOUNT_ID INT NOT NULL,
    TITLE_ID VARCHAR(20) NOT NULL,
    TITLE_QUEUED_DATE DATETIME NOT NULL,
    TITLE_REMOVE_QUEUED_DATE DATETIME NULL,
    TITLE_RATING INT NULL,
    CONSTRAINT PK_ACCOUNT_TITLES PRIMARY KEY (TITLE_ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID INT NOT NULL,
    ACCOUNT_EMAIL VARCHAR(200) NOT NULL,
    ACCOUNT_PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS CASTING (
    CAST_PEOPLE_ID INT NOT NULL,
    CAST_TITLE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CASTING PRIMARY KEY (CAST_PEOPLE_ID, CAST_TITLE_ID)
);

CREATE TABLE IF NOT EXISTS DIRECTORS (
    DIRECTOR_PEOPLE_ID INT NOT NULL,
    DIRECTOR_TITLE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DIRECTORS PRIMARY KEY (DIRECTOR_PEOPLE_ID, DIRECTOR_TITLE_ID)
);

CREATE TABLE IF NOT EXISTS GENRES (
    GENRE_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_GENRES PRIMARY KEY (GENRE_NAME)
);

CREATE TABLE IF NOT EXISTS PEOPLE (
    PEOPLE_ID INT NOT NULL,
    PEOPLE_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PK_PEOPLE PRIMARY KEY (PEOPLE_ID)
);

CREATE TABLE IF NOT EXISTS PLANS (
    PLAN_ID INT NOT NULL,
    PLAN_NAME VARCHAR(50) NOT NULL,
    PLAN_PRICE DECIMAL(5,2) NOT NULL,
    PLAN_CURRENT BOOLEAN NOT NULL,
    DISCOUNT DECIMAL(5,2) NULL,
    CONSTRAINT PK_PLANS PRIMARY KEY (PLAN_ID)
);

CREATE TABLE IF NOT EXISTS TITLE_GENRES (
    GENRE_NAME VARCHAR(200) NOT NULL,
    TITLE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TITLE_GENRES PRIMARY KEY (GENRE_NAME, TITLE_ID)
);

CREATE TABLE IF NOT EXISTS TITLES (
    TITLE_ID VARCHAR(20) NOT NULL,
    TITLE_NAME VARCHAR(300) NOT NULL,
    TITLE_TYPE VARCHAR(20) NOT NULL,
    TITLE_SYNOPSIS VARCHAR(50000) NOT NULL,
    TITLE_AVG_RATING DECIMAL(3,2) NOT NULL,
    TITLE_RELEASE_YEAR INT NOT NULL,
    TITLE_RUNTIME INT NOT NULL,
    TITLE_RATING VARCHAR(20) NOT NULL,
    TITLE_BLURAY_AVAILABLE BOOLEAN NOT NULL,
    TITLE_DATE_MODIFIED DATE NOT NULL,
    CONSTRAINT PK_TITLES PRIMARY KEY (TITLE_ID)
);

-- foreign keys
ALTER TABLE ACCOUNT_ACTIVITY 
ADD CONSTRAINT FK_ACCOUNT_ACTIVITY_ACCOUNTS 
FOREIGN KEY (ACCOUNT_ID) 
REFERENCES ACCOUNTS (ACCOUNT_ID);

ALTER TABLE ACCOUNT_BILLING 
ADD CONSTRAINT FK_ACCOUNT_BILLING_ACCOUNTS 
FOREIGN KEY (ACCOUNT_ID) 
REFERENCES ACCOUNTS (ACCOUNT_ID);

ALTER TABLE ACCOUNT_BILLING 
ADD CONSTRAINT FK_ACCOUNT_BILLING_PLANS 
FOREIGN KEY (PLAN_ID) 
REFERENCES PLANS (PLAN_ID);

ALTER TABLE ACCOUNT_TITLES 
ADD CONSTRAINT FK_ACCOUNT_TITLES_ACCOUNTS 
FOREIGN KEY (TITLE_ACCOUNT_ID) 
REFERENCES ACCOUNTS (ACCOUNT_ID);

ALTER TABLE ACCOUNT_TITLES 
ADD CONSTRAINT FK_ACCOUNT_TITLES_TITLES 
FOREIGN KEY (TITLE_ID) 
REFERENCES TITLES (TITLE_ID);

ALTER TABLE TITLE_GENRES 
ADD CONSTRAINT FK_TITLE_GENRES_GENRES 
FOREIGN KEY (GENRE_NAME) 
REFERENCES GENRES (GENRE_NAME);

ALTER TABLE CASTING 
ADD CONSTRAINT FK_CASTING_PEOPLE 
FOREIGN KEY (CAST_PEOPLE_ID) 
REFERENCES PEOPLE (PEOPLE_ID);

ALTER TABLE CASTING 
ADD CONSTRAINT FK_CASTING_TITLES 
FOREIGN KEY (CAST_TITLE_ID) 
REFERENCES TITLES (TITLE_ID);

ALTER TABLE DIRECTORS 
ADD CONSTRAINT FK_DIRECTORS_PEOPLE 
FOREIGN KEY (DIRECTOR_PEOPLE_ID) 
REFERENCES PEOPLE (PEOPLE_ID);

ALTER TABLE DIRECTORS 
ADD CONSTRAINT FK_DIRECTORS_TITLES 
FOREIGN KEY (DIRECTOR_TITLE_ID) 
REFERENCES TITLES (TITLE_ID);

ALTER TABLE TITLE_GENRES 
ADD CONSTRAINT FK_TITLE_GENRES_TITLES 
FOREIGN KEY (TITLE_ID) 
REFERENCES TITLES (TITLE_ID);


